name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build -c:Release -o:$(pwd)/publish
      - name: Pack
        run: dotnet pack -c:Release -o:$(pwd)/publish
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: $(pwd)/publish
          retention-days: 1
      - name: Publish
        run: dotnet nuget push $(pwd)/publish/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
