name: Documentation

on:
  push:
    branches: [master]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Install tools
        run: |
          dotnet tool install --global SourceLinkExtract
          dotnet tool install --global SourceSymbolMapper
          dotnet tool install --global XmlDocMdSymbols

      - name: Build
        run: dotnet build -f:net60 -c:Release -o:publish

      - name: Copy README file
        run: cat ./README.md > ./docs/index.md

      - name: Generate markdown book
        run: ./.github/generate_docs.sh

      - name: Deploy book
        run: mkdocs gh-deploy --force
